[run]
  deadline = "3m"
  skip-files = []

[linters-settings]

  [linters-settings.govet]
    check-shadowing = true

  [linters-settings.gocyclo]
    min-complexity = 12.0

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 3.0

  [linters-settings.misspell]
    locale = "US"

  [linters-settings.funlen]
    lines = 110 # default 60
    statements = 60 # default 40

[linters]
  enable-all = true
  disable = [
    "maligned",
    "lll",
    "gas",
    "dupl",
    "prealloc",
    "scopelint",
    "typecheck", # v1.17.1 and Go1.13 => bug
  ]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same-issues = 0
  exclude = []
  [[issues.exclude-rules]]
    path = "flaeg.go"
    text = "cyclomatic complexity (\\d+) of func `(fillStructRecursive|getDefaultValue|getTypesRecursive)` is high"
  [[issues.exclude-rules]]
    path = "flaeg_test.go"
    text = "(type )?`(other|unexported|SubSubConfig)` is unused"
  [[issues.exclude-rules]]
    path = "flaeg_test.go"
    text = "string `(DefaultOwnerNamePointer|INFO)` has (\\d+) occurrences, make it a constant"
